---
# tasks file for roles/database
- name: Run Database
  docker_container:
    name: postgres
    image: lazarec/postgres:latest
    networks:
      - name: "{{ docker_network_name }}"
    env:
      POSTGRES_DB: "{{ db_db }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_pass }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
