version: "3.7"

services:
  backend:
    image: lazarec/backend:latest
    networks:
      - my-network
    env_file: .env
    depends_on:
      - database
    hostname: backend

  database:
    image: lazarec/postgres:latest
    networks:
      - my-network
    volumes:
      - devops-postgres:/var/lib/postgresql/data
    env_file: .env
    hostname: postgres

  front:
    image: lazarec/front:latest
    networks:
      - my-network
    env_file: .env
    hostname: front

  httpd:
    image: lazarec/proxy:latest
    ports:
      - "80:80"
    networks:
      - my-network
    env_file: .env
    depends_on:
      - backend
    hostname: proxy

networks:
  my-network:

volumes:
  devops-postgres:
