---
# tasks file for roles/front
- name: Run Front
  docker_container:
    name: front
    image: lazarec/front:latest
    networks:
      - name: "{{ docker_network_name }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3