name: Test Backend
on:
  #to begin you want to launch this job in main and develop
  push:
    # on donne les branches à tester (la develop existe pas encore)
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
      # on utilise l'action setup java officiel
        uses: actions/setup-java@v4
        with:
          # on utilise le même jdk que le Dockerfile
          distribution: 'corretto'
          # on précise la même version que le Dockerfile
          java-version: '17'

      #finally build your app with the latest command
      - name: Build and test with Maven
        #on run maven clean verify dans le dossier du backend
        #run: mvn clean verify --file ./backend/
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=le-test_ici-ca-test -Dsonar.organization=le-test -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./backend/pom.xml


  # define job to build and publish docker image